[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['npm install --omit=dev --no-audit --no-fund']

[phases.build]
cmds = ['cd game-ssr && npm install --omit=dev --no-audit --no-fund', 'cd game-ssr && npm run build:minimal']

[start]
cmd = 'node simple-server.js'