[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['npm install --omit=dev --no-audit --no-fund']

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'node server-simple.js'