// Типы для системы комнат Energy of Money (JavaScript версия)

// Коды ошибок для комнат
export const RoomErrorCode = {
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_FULL: 'ROOM_FULL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  PROFESSION_NOT_AVAILABLE: 'PROFESSION_NOT_AVAILABLE',
  PROFESSION_ALREADY_TAKEN: 'PROFESSION_ALREADY_TAKEN',
  INVALID_SELECTION_MODE: 'INVALID_SELECTION_MODE',
  SELECTION_TIMEOUT: 'SELECTION_TIMEOUT',
  PLAYER_NOT_IN_ROOM: 'PLAYER_NOT_IN_ROOM',
  ROOM_ALREADY_STARTED: 'ROOM_ALREADY_STARTED',
  INVALID_PLAYER_DATA: 'INVALID_PLAYER_DATA',
  DATABASE_ERROR: 'DATABASE_ERROR'
};

// Коды ошибок для профессий
export const ProfessionErrorCode = {
  PROFESSION_NOT_AVAILABLE: 'PROFESSION_NOT_AVAILABLE',
  PROFESSION_ALREADY_TAKEN: 'PROFESSION_ALREADY_TAKEN',
  INVALID_SELECTION_MODE: 'INVALID_SELECTION_MODE',
  SELECTION_TIMEOUT: 'SELECTION_TIMEOUT',
  PLAYER_NOT_IN_ROOM: 'PLAYER_NOT_IN_ROOM',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND'
};
