[build]
builder = "nixpacks"

[deploy]
startCommand = "chmod +x build-minimal.sh && ./build-minimal.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_OPTIONS = "--max-old-space-size=8192"
NODE_ENV = "production"
